### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/xml/bind/api/ErrorListener for JAXB v2.2.11 

### ISSUE THREAD

**Issue by ghost** [jacobono/gradle-jaxb-plugin#15]
```
    apply plugin: 'com.github.jacobono.jaxb'

    dependencies {
        jaxb 'com.sun.xml.bind:jaxb-xjc:2.2.11'
        jaxb 'com.sun.xml.bind:jaxb-impl:2.2.11'
        jaxb 'javax.xml.bind:jaxb-api:2.2.11'
    }

    10:07:01.752 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] Class org.xml.sax.ErrorHandler loaded from parent loader (parentFirst)
    10:07:01.762 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] Resource com/sun/tools/xjc/api/ErrorListener.class loaded from ant loader
    10:07:01.782 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] Couldn't load Resource com/sun/xml/bind/api/ErrorListener.class
    10:07:01.792 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':iqpdct-iodd101:xjc'
    10:07:01.802 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :iqpdct-iodd101:xjc FAILED
    10:07:01.822 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :iqpdct-iodd101:xjc (Thread[main,5,main]) completed. Took 1.972 secs.
    10:07:01.832 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 3.137 secs, idle: 0.038 secs
    10:07:01.842 [ERROR] [org.gradle.BuildExceptionReporter]
    10:07:01.852 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
    10:07:01.862 [ERROR] [org.gradle.BuildExceptionReporter]
    10:07:01.872 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
    10:07:01.882 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':iqpdct-iodd101:xjc'.
    10:07:01.892 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NoClassDefFoundError: com/sun/xml/bind/api/ErrorListener
    10:07:01.902 [ERROR] [org.gradle.BuildExceptionReporter]
    10:07:01.912 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
    10:07:01.922 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
    10:07:01.942 [LIFECYCLE] [org.gradle.BuildResultLogger]
    10:07:01.942 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

**Comment by Steve-Murphy** [comment]
Thanks a million for this.

**Comment by benmccann** [comment]
I filed a bug on the JAXB JIRA here: https://java.net/jira/browse/JAXB-1070

**Comment by ghost** [comment]
Hey, I am refereeing to the same error from `http://stackoverflow.com/questions/30084367/spring-oauth2-wso2-integration-example`. for that I added following dependency 

`<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.2.12</version>
</dependency>`

But still I see following error comming. Could you please guide me ASAP? As I am unable to resolved this error from last 3+ weeks.

`Execution default of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed: A required class 
 was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate: com/sun/xml/bind/
 api/ErrorListener ----------------------------------------------------- realm = 
 plugin>org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3 strategy = 
 org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy urls[0] = file:/C:/Users/prateek/.m2/repository/org/
 jvnet/jaxb2/maven2/maven-jaxb2-plugin/0.12.3/maven-jaxb2-plugin-0.12.3.jar urls[1] = file:/C:/Users/
 prateek/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb2-plugin-core/0.12.3/maven-jaxb2-plugin-
 core-0.12.3.jar urls[2] = file:/C:/Users/prateek/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar urls[3] 
 = file:/C:/Users/prateek/.m2/repository/org/apache/commons/commons-lang3/3.2.1/commons-
 lang3-3.2.1.jar urls[4] = file:/C:/Users/prateek/.m2/repository/com/sun/org/apache/xml/internal/resolver/
 20050927/resolver-20050927.jar urls[5] = file:/C:/Users/prateek/.m2/repository/junit/junit/4.8.1/junit-4.8.1.jar 
 urls[6] = file:/C:/Users/prateek/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar 
 urls[7] = file:/C:/Users/prateek/.m2/repository/org/jvnet/jaxb2/maven2/maven-jaxb22-plugin/0.12.3/maven-
 jaxb22-plugin-0.12.3.jar urls[8] = file:/C:/Users/prateek/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.2.11/
 jaxb-runtime-2.2.11.jar urls[9] = file:/C:/Users/prateek/.m2/repository/org/glassfish/jaxb/jaxb-xjc/2.2.11/jaxb-
 xjc-2.2.11.jar urls[10] = file:/C:/Users/prateek/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-
 annotations/3.2/maven-plugin-annotations-3.2.jar Number of foreign imports: 5 import: Entry[import 
 org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]] import: Entry[import 
 org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]] import: Entry[import 
 org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]] import: 
 Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]] 
 import: Entry[import from realm ClassRealm[maven.api, parent: null]] 
 ----------------------------------------------------- (org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:
 0.12.3:generate:default:generate-sources)`

**Comment by easybird** [comment]
A "better" solution would be to use the correct new dependencies of jaxb:
- 'org.glassfish.jaxb:jaxb-xjc:2.2.11'
- 'org.glassfish.jaxb:jaxb-runtime:2.2.11'

When using those 2 dependencies only, and removing all the legacy 'com.sun.xml.bind' dependencies, the above problem will be fixed.

To avoid confusion, it would be better to specify those dependencies in the README file.

**Comment by Kamapcuc** [comment]
java -cp jaxb-impl-2.2.7.jar -jar jaxb-xjc-2.2.7.jar --version
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/xml/bind/api/ErrorListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at com.sun.istack.tools.ParallelWorldClassLoader.findClass(ParallelWorldClassLoader.java:158)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getDeclaredMethod(Unknown Source)
        at com.sun.tools.xjc.XJCFacade.main(XJCFacade.java:76)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.api.ErrorListener
        at com.sun.istack.tools.ParallelWorldClassLoader.findClass(ParallelWorldClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 10 more
```

**Comment by joseam84** [comment]
I fixed this error by making Eclipse run with the latest jdk vm. This was done adding the -vm parameter to the eclipse.ini file since my computer set up is running an older JDK (set in JAVA_HOME) for some other tools I have that require it.
