### ISSUE TITLE
unresolved dependencies

### ISSUE THREAD

**Issue by wlund-pivotal** [jacobono/gradle-jaxb-plugin#21]
I can't seem to get past this error on gradle build:

 Searched in the following locations:
         https://jcenter.bintray.com/org/gradle/jacobo/gradle-xsd-wsdl-slurping/1.1.1/gradle-xsd-wsdl-slurping-1.1.1.pom
         https://jcenter.bintray.com/org/gradle/jacobo/gradle-xsd-wsdl-slurping/1.1.1/gradle-xsd-wsdl-slurping-1.1.1.jar
         https://repo1.maven.org/maven2/org/gradle/jacobo/gradle-xsd-wsdl-slurping/1.1.1/gradle-xsd-wsdl-slurping-1.1.1.pom
         https://repo1.maven.org/maven2/org/gradle/jacobo/gradle-xsd-wsdl-slurping/1.1.1/gradle-xsd-wsdl-slurping-1.1.1.jar
     Required by:
         :gfexpert:unspecified > org.gradle.jacobo.plugins:gradle-jaxb-plugin:1.3.4
         :gfexpert:unspecified > org.gradle.jacobo.plugins:gradle-wsdl-plugin:1.7.6

What am I missing:

    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		classpath 'org.gradle.jacobo.plugins:gradle-jaxb-plugin:1.3.4' 
		classpath 'org.gradle.jacobo.plugins:gradle-wsdl-plugin:1.7.6'    
	}

apply plugin: 'com.github.jacobono.jaxb'

dependencies {
	jaxb 'com.sun.xml.bind:jaxb-xjc:2.2.7-b41'
	jaxb 'com.sun.xml.bind:jaxb-impl:2.2.7-b41'
	jaxb 'javax.xml.bind:jaxb-api:2.2.7'
etc

I can't get it to work for me.

**Comment by jacobono** [comment]
This should be all fixed now

**Comment by eferreyramontes** [comment]
Having similar issue now. I can check that the dependency is not in https://plugins.gradle.org/m2/com/github/jacobono/.

The issue now is with `gradle-xsd-wsdl-slurping` version `1.1.2`:

```java
Could not resolve all artifacts for configuration ':classpath'.
Could not find com.github.jacobono:gradle-xsd-wsdl-slurping:1.1.2.
Searched in the following locations:
https://plugins.gradle.org/m2/com/github/jacobono/gradle-xsd-wsdl-slurping/1.1.2/gradle-xsd-wsdl-slurping-1.1.2.pom
command output: If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
project : > com.github.jacobono.jaxb:com.github.jacobono.jaxb.gradle.plugin:1.3.5 > com.github.jacobono:gradle-jaxb-plugin:1.3.5
```

Can you help me @jacobono?
