### ISSUE TITLE
How to specify xjc extensions?

### ISSUE THREAD

**Issue by davidmichaelkarr** [jacobono/gradle-jaxb-plugin#23]
I see that you can set the "extension mode" flag, but how do you specify the extensions to use, and the arguments to those extensions?  For instance, in the Maven "cxf-xjc-plugin" plugin, I can specify an "extensions" section in the configuration where specify the GAV tuples for my extensions, and then in the "xsdOptions" section, I can specify "extensionArgs" with the command line options for those extensions.

**Comment by jacobono** [comment]
That extension flag is **just** for the [xjc ant task](https://jaxb.java.net/2.2.4/docs/xjcTask.html)

It is just a mode flag
> Run XJC compiler in extension mode

I don't know anything about the maven plugin you mentioned, but I don't think there is that type of extensions with this plugin.

**Comment by davidmichaelkarr** [comment]
There are quite a few extensions that can be used with JAXB.  The particular extension I'm trying to use is at: https://github.com/dmak/jaxb-xew-plugin .  Using any JAXB plugin requires adding to the JAXB classpath, but it often requires adding additional args to the xjc command line.

**Comment by jacobono** [comment]
the readme has a [section using jaxb 2](https://github.com/jacobono/gradle-jaxb-plugin/blob/master/README.md#default-example-using-jaxb2) that I think will do what you want.
