### ISSUE TITLE
How to specify specific XSDs and packages for each?

### ISSUE THREAD

**Issue by davidmichaelkarr** [jacobono/gradle-jaxb-plugin#24]
The default config and doc shows how to process all the XSDs in a folder to a particular package.  How do I specify individual XSD files and a different package for each one?  All of them are in the same folder.

**Comment by jacobono** [comment]
you can't specify individual files.

You have two options

- all xsds have a `targetNamespace` attribute, that will put them in packages based on that value and don't put a `package` name at all
- break up xsds into `N` individual folders with xsds that go in a particular package and have `N` projects that parse the `N` xsd folders 1-to-1

**Comment by davidmichaelkarr** [comment]
That's unfortunate. My goal and requirement at this point is to implement the Gradle build without changing anything in the application. I guess I'm going to have to look at more manual steps to get this done in the Gradle build.

If you were going to design this feature, I would suggest you allow a "xsdFile" property in the "xjc" object, and your processing step would expect only one of "xsdFile" or "xsdDir" to be set (with one of them taking precedence).  I would assume that is all that's needed.

**Comment by jacobono** [comment]
Sorry this doesn't do what you want.

I'm closing this issue as it isn't really an issue.
