### ISSUE TITLE
TreeNodeSpec unit test fails with verify error

### ISSUE THREAD

**Issue by davidmichaelkarr** [jacobono/gradle-jaxb-plugin#25]
I forked and cloned master, and when I finally built it, a unit test failed with the following:

java.lang.VerifyError: (class: org/gradle/jacobo/plugins/tree/TreeNode$1, method: super$1$sort signature: (Ljava/util/Comparator;)V) Illegal use of nonvirtual function call
	at org.gradle.jacobo.plugins.tree.TreeNode.<init>(TreeNode.groovy:65)
	at org.gradle.jacobo.plugins.tree.TreeNodeSpec.Create node with data, and one parent(TreeNodeSpec.groovy:31)

Looking at TreeNode.groovy:

  public TreeNode(T data, TreeNode<T> parent) {
    this.parents = new LinkedList<TreeNode<T>>() {{ add(parent) }} // line 65
    this.children = new LinkedList<TreeNode<T>>()
    this.data = data
    parent.addChild(this, false)
  }

I'm not yet a native Groovy speaker (compared to Java), so I'm not sure what's going on here. When I commented out the single "Create node with data, and one parent" test, the build succeeded.

I tried various hacks that were implied on the internet, like adding "-Xverify:none".  I tried setting the JDK compile level to 1.6, 1.7, and 1.8.  No change.

**Comment by jacobono** [comment]
master builds and tests fine.

You must have changed something for it to fail -- the question is what?

**Comment by davidmichaelkarr** [comment]
I forked the project and cloned it to my desktop, then I attempted to build it.  That's it.

I'm doing this on Windows 7. What platform are you building on?

**Comment by jacobono** [comment]
mac or linux.

Windows builds might be uncharted territory. :(
