### ISSUE TITLE
xsdDir cannot support subproject

### ISSUE THREAD

**Issue by blackumbrella** [jacobono/gradle-jaxb-plugin#33]
my project structure is like:
Root
|-Folder 1
     |--subsubproject 1

In my build.gradle I set xsdDir to /src/resources/schema.
In runtime I got error as:
Could not normalize path for file Root\src\resources\schema. 

Seems the the folder and subproject name are skipped.

**Comment by scubacabra** [comment]
This is by design.  The xsd Dir is always relative to the root directory.

xsdDir as `Folder 1/subsubproject 1/src/resources/schema` should work.
