### ISSUE TITLE
toString, equals, hashcode

### ISSUE THREAD

**Issue by ianbarile** [jacobono/gradle-jaxb-plugin#38]
Would be great to support the following "toString, equals, hashcode" similar to jaxb2basics plugn

https://github.com/highsource/jaxb2-basics/wiki/Using-JAXB2-Basics-Plugins

**Comment by scubacabra** [comment]
You should already be able to.

https://github.com/jacobono/gradle-jaxb-plugin#default-example-using-jaxb2

**Comment by ianbarile** [comment]
Tried that. doesn't seem to support it.

***\* error ****
- Where:
  Build file '/Users/ian/source/git/lendsnow/server/projects/transaction/build.gradle' line: 87
- What went wrong:
  A problem occurred evaluating project ':transaction'.
  
  > Could not find property 'Xequals' on org.gradle.jacobo.plugins.extension.XjcExtension_Decorated@798deee8.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

****\* snippet from build.gradle ******
jaxb {
  xsdDir = "${name}/schema/"
  episodesDir = "${buildDir}/schema"
  bindingsDir = "${name}/schema/bindings"
  xjc {
    destinationDir = "../build/transaction/generatedsrc/"
    taskClassname = "org.jvnet.jaxb2_commons.xjc.XJC2Task"
    args = ["-Xannotate", -Xequals, -XhashCode, -XtoString]
  }
}

**Comment by scubacabra** [comment]
``` groovy
 args = ["-Xannotate", -Xequals, -XhashCode, -XtoString]
```

Needs to be

``` groovy
 args = ["-Xannotate", "-Xequals", "-XhashCode", "-XtoString"]
```

**Comment by ianbarile** [comment]
Thanks.
